 # Conda environment for Gammapy version 0.20.1
# Install:    conda env create -f gammapy-0.20.1-environment.yml
# Activate:   conda activate gammapy-0.20.1
# Deactivate: conda deactivate

name: gammapy-0.20.1

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - gammapy=0.20.1
  - python=3.8
  - ipython=8.3
  - cython
  - jupyter
  - jupyterlab=3.4.0
  - pyyaml=6.0
  - click=8.1.3
  - numpy=1.22.3
  - scipy=1.8.0
  - pandas=1.4.2
  - matplotlib=3.5.2
  - astropy=5.0
  - regions=0.6
  - iminuit=2.11.2
  - sherpa=4.14.0
  - healpy=1.15
  - naima=0.10.0
  - pydantic=1.9.0
  - emcee=3.1.1
  - corner=2.2.1
  - pip
  - requests