general:
    log: {level: info, filename: null, filemode: null, format: null, datefmt: null}
    outdir: .
    n_jobs: 1
    datasets_file: null
    models_file: null
observations:
    datastore: $GAMMAPY_DATA/cta-1dc/index/gps
    obs_ids: [110380, 111140, 111159]
    obs_file: null
    obs_cone: {frame: null, lon: null, lat: null, radius: null}
    obs_time: {start: null, stop: null}
    required_irf: [aeff, edisp, psf, bkg]
datasets:
    type: 3d
    stack: true
    geom:
        wcs:
            skydir: {frame: galactic, lon: 0.0 deg, lat: 0.0 deg}
            binsize: 0.02 deg
            width: {width: 10.0 deg, height: 8.0 deg}
            binsize_irf: 0.2 deg
        selection: {offset_max: 3.5 deg}
        axes:
            energy: {min: 0.1 TeV, max: 10.0 TeV, nbins: 10}
            energy_true: {min: 0.08 TeV, max: 12.0 TeV, nbins: 14}
    map_selection: [counts, exposure, background, psf, edisp]
    background:
        method: null
        exclusion: null
        parameters: {}
    safe_mask:
        methods: [aeff-default, offset-max]
        parameters: {}
    on_region: {frame: null, lon: null, lat: null, radius: null}
    containment_correction: true
fit:
    fit_range: {min: null, max: null}
flux_points:
    energy: {min: null, max: null, nbins: null}
    source: source
    parameters: {selection_optional: all}
excess_map:
    correlation_radius: 0.1 deg
    parameters: {}
    energy_edges: {min: null, max: null, nbins: null}
light_curve:
    time_intervals: {start: null, stop: null}
    energy_edges: {min: null, max: null, nbins: null}
    source: source
    parameters: {selection_optional: all}
