# Conda environment for Gammapy version 1.0
# Install:    conda env create -f gammapy-1.0-environment.yml
# Activate:   conda activate gammapy-1.0
# Deactivate: conda deactivate

name: gammapy-1.0

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - gammapy=1.0
  - python=3.9
  - ipython=8.4
  - cython
  - jupyter
  - jupyterlab=3.4.8
  - pyyaml=6.0
  - click=8.1.3
  - numpy=1.23
  - scipy=1.9.1
  - pandas=1.5.0
  - matplotlib=3.6.2
  - astropy=5.1
  - regions=0.6
  - iminuit=2.17
  - sherpa=4.15.0
  - healpy=1.16.1
  - naima=0.10.0
  - pydantic=1.9.0
  - emcee=3.1.3
  - corner=2.2.1
  - pip
  - requests
  - tqdm



    